language: objective-c
osx_image: xcode10.2
podfile: Podfile
xcode_workspace: ooniprobe.xcworkspace
xcode_scheme: ooniprobe
xcode_sdk: iphonesimulator
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone Xs Max
before_install:
  - bundle install
  - pod repo update
  - pod install
script:
#  - xcodebuild -workspace ooniprobe.xcworkspace/ -scheme ooniprobe CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
#  - xcodebuild clean test -workspace ooniprobe.xcworkspace/ -sdk iphonesimulator -scheme OONIProbeUITests -destination 'name=iPhone Xs Max' CODE_SIGNING_REQUIRED=NO | xcpretty
#  - xcodebuild clean test -workspace ooniprobe.xcworkspace/ -sdk iphonesimulator -scheme ooniprobe -destination 'name=iPhone Xs Max'  | xcpretty
#  - xcodebuild clean test -workspace ooniprobe.xcworkspace/ -sdk iphonesimulator  -scheme ooniprobe -destination 'name=iPhone Xs Max' CODE_SIGNING_REQUIRED=NO -only-testing:OONIProbeUnitTests | xcpretty
  - xcodebuild clean test | xcpretty
