language: objective-c
osx_image: xcode10.2
podfile: Podfile

env:
  - NODE_VERSION="12.13"

before_install:
  - brew install gradle
  - nvm install $NODE_VERSION
  - bundle install
  - pod repo update
  - pod install
  - git clone https://github.com/ooni/probe-mobile-appium.git

script:
  - set -o pipefail && xcodebuild clean build test -workspace ooniprobe.xcworkspace/ -sdk iphonesimulator -scheme ooniprobe -destination 'name=iPhone Xs Max'  | xcpretty
  - cd probe-mobile-appium && gradle iosRegression

