language: objective-c
osx_image: xcode11.1
podfile: Podfile
jdk: oraclejdk8

env:
  global:
#    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - NODE_VERSION="12.13"
#    - PATH=${JAVA_HOME}/bin:$PATH

before_install:
  - brew install gradle
  - nvm install $NODE_VERSION
  - brew tap wix/brew
  - brew install applesimutils
  - bundle install
  - pod repo update
  - pod install
  - echo $JAVA_HOME
  - echo $PATH

before_script:
  - npm install appium -g
#  - npm install -g appium-doctor
  - git clone https://github.com/ooni/probe-mobile-appium.git
#  - appium-doctor --ios
#  - appium --log-level info > $HOME/appium_log.txt &

script:
  - set -o pipefail && xcodebuild clean build test -workspace ooniprobe.xcworkspace/ -sdk iphonesimulator -scheme ooniprobe -destination 'name=iPhone 11 Pro Max'  | xcpretty
  - cd probe-mobile-appium && gradle iosRegression
#  - cat $HOME/appium_log.txt
  - cat /Users/travis/build/ooni/probe-ios/probe-mobile-appium/build/reports/tests/iosRegression/classes/probe.mobile.appium.runners.LandingPageRunner.html
