language: objective-c
osx_image: xcode11.1
podfile: Podfile

env:
  - NODE_VERSION="12.13"

before_install:
  - brew install gradle
#  - nvm install $NODE_VERSION
#  - npm install -g appium
#  - npm install appium-doctor -g
#  - npm i -g opencv4nodejs
#  - brew tap wix/brew
#  - brew install applesimutils
#  - brew tap facebook/fb
#  - brew install idb-companion
  - bundle install
  - pod repo update
  - pod install
#  - git clone https://github.com/ooni/probe-mobile-appium.git

before_script:
  - nvm install $NODE_VERSION
  - npm install -g appium
  - npm install -g appium-doctor
  - git clone https://github.com/ooni/probe-mobile-appium.git
  - appium  -v
  - appium-doctor --ios

script:
  - set -o pipefail && xcodebuild clean build test -workspace ooniprobe.xcworkspace/ -sdk iphonesimulator -scheme ooniprobe -destination 'name=iPhone 11 Pro Max'  | xcpretty
  - appium &
  - cd probe-mobile-appium && gradle iosRegression
  - cat /Users/travis/build/ooni/probe-ios/probe-mobile-appium/build/reports/tests/iosRegression/classes/probe.mobile.appium.runners.LandingPageRunner.html
