language: objective-c
osx_image: xcode11.2
podfile: Podfile
#jdk: oraclejdk8
node_js: 
  - '10'
rvm:
  - '2.4.3'

env:
  global:
#    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - NODE_VERSION="10.15"
#    - PATH=${JAVA_HOME}/bin:$PATH

before_install:
  - brew update
  - brew install gradle
#  - nvm install $NODE_VERSION
  - node -v
  - brew tap wix/brew
  - brew install applesimutils
  - bundle install
  - pod repo update
  - pod install

before_script:
  - npm install appium -g
  - npm install -g appium-doctor
  - git clone https://github.com/ooni/probe-mobile-appium.git
  - appium-doctor --ios
#  - appium --log-level info > $HOME/appium_log.txt &

script:
  - set -o pipefail && xcodebuild clean build test -workspace ooniprobe.xcworkspace/ -sdk iphonesimulator -scheme ooniprobe -destination 'name=iPhone 11 Pro Max'  | xcpretty
  - cd probe-mobile-appium && gradle iosRegression
#  - cat $HOME/appium_log.txt
  - cat /Users/travis/build/ooni/probe-ios/probe-mobile-appium/build/reports/tests/iosRegression/classes/probe.mobile.appium.runners.LandingPageRunner.html
