language: objective-c
osx_image: xcode10.2
podfile: Podfile
before_install:
  - bundle install
  - pod repo update
  - pod install
script:
  - set -o pipefail && xcodebuild clean build test -workspace ooniprobe.xcworkspace/ -sdk iphonesimulator -scheme ooniprobe -destination 'name=iPhone Xs Max'  | xcpretty
