name: archive
on:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * */2"
jobs:
  archive:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle install
      - run: pod repo update
      - run: pod install
      - run: |
          set -o pipefail
          xcodebuild -workspace ooniprobe.xcworkspace -scheme ooniprobe \
            -destination='name=Any iOS Device' -sdk iphoneos archive CODE_SIGNING_ALLOWED="NO" | xcpretty
        env:
          DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
