name: tests
on:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * */2"
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle install
      - run: pod repo update
      - run: pod install
      - run: xcrun simctl list --json devices available
      - run: |
          set -o pipefail
          xcodebuild clean build test -verbose -workspace ooniprobe.xcworkspace -sdk iphonesimulator \
            -scheme ooniprobe -destination 'name=iPhone 13 mini'
        env:
          DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
