name: tests
on:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * */2"
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: bundle install
      - run: pod repo update
      - run: pod install
      - run: |
          set -o pipefail
          xcodebuild clean build test -workspace ooniprobe.xcworkspace -sdk iphonesimulator \
            -scheme ooniprobe -destination 'name=iPhone 14' | xcpretty
        env:
-          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
