name: Validate
on:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * */2"

jobs:
  build:
    name: Ensure the code builds
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: pod repo update
      - run: pod install
      - run: |
          set -o pipefail
          xcodebuild -workspace ooniprobe.xcworkspace -scheme ooniprobe \
            -destination='name=Any iOS Device' -sdk iphoneos archive CODE_SIGNING_ALLOWED="NO" | xcpretty

  test:
    name: Run tests
    needs: [ build ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: pod repo update
      - run: pod install
      - run: |
          set -o pipefail
          xcodebuild clean build test -workspace ooniprobe.xcworkspace -sdk iphonesimulator \
            -scheme ooniprobe -destination 'name=iPhone 14' | xcpretty
